on: [push, pull_request, workflow_dispatch]

name: Build

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build (Legacy)
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Get version data
        id: get_info
        env:
          GH_SHA: ${{ github.sha }}
          GH_REF: ${{ github.ref }}
        run: |
          timestamp=$(date +"%Y%m%d%H%M")
          commit=$(echo "$GH_SHA" | cut -c1-7)
          file_prefix=$timestamp-$commit
          branch_name=$(echo "$GH_REF" | awk -F'/' '{print $3}' | cut -c1-4)
          echo "file_prefix=$file_prefix" >> $GITHUB_OUTPUT
          bin/get_version.sh $branch_name $commit
      - name: Cache west modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (left)
        run: west build -s zmk/app -d build/left -b adv360_left -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Adv360 Left Kconfig file
        run: grep -vE '(^#|^$)' build/left/zephyr/.config
      - name: West Build (right)
        run: west build -s zmk/app -d build/right -b adv360_right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Adv360 Right Kconfig file
        run: grep -vE '(^#|^$)' build/right/zephyr/.config
      - name: Rename zmk.uf2
        run: cp build/left/zephyr/zmk.uf2 ${{ steps.get_info.outputs.file_prefix }}-left.uf2 && cp build/right/zephyr/zmk.uf2 ${{ steps.get_info.outputs.file_prefix }}-right.uf2
      - name: Archive (Adv360)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: firmware-no-clique
          path: |
            ${{ steps.get_info.outputs.file_prefix }}-left.uf2
            ${{ steps.get_info.outputs.file_prefix }}-right.uf2
  build-clique:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build (Clique)
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Get version data
        id: get_info
        env:
          GH_SHA: ${{ github.sha }}
          GH_REF: ${{ github.ref }}
        run: |
          timestamp=$(date +"%Y%m%d%H%M")
          commit=$(echo "$GH_SHA" | cut -c1-7)
          file_prefix=$timestamp-$commit
          branch_name=$(echo "$GH_REF" | awk -F'/' '{print $3}' | cut -c1-4)
          echo "file_prefix=$file_prefix" >> $GITHUB_OUTPUT
          bin/get_version.sh $branch_name $commit clique
      - name: Cache west modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (left)
        run: west build -s zmk/app -d build/left -b adv360_left -S studio-rpc-usb-uart -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DCONFIG_ZMK_STUDIO=y
      - name: Adv360 Left Kconfig file
        run: grep -vE '(^#|^$)' build/left/zephyr/.config
      - name: West Build (right)
        run: west build -s zmk/app -d build/right -b adv360_right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Adv360 Right Kconfig file
        run: grep -vE '(^#|^$)' build/right/zephyr/.config
      - name: Rename zmk.uf2
        run: cp build/left/zephyr/zmk.uf2 ${{ steps.get_info.outputs.file_prefix }}-left.uf2 && cp build/right/zephyr/zmk.uf2 ${{ steps.get_info.outputs.file_prefix }}-right.uf2
      - name: Archive (Adv360)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: firmware-clique
          path: |
            ${{ steps.get_info.outputs.file_prefix }}-left.uf2
            ${{ steps.get_info.outputs.file_prefix }}-right.uf2
